# Generated by Django 4.0.2 on 2022-10-25 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='textapp.product')),
            ],
        ),
    ]
