# Generated by Django 4.0.2 on 2022-10-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0004_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Index',
        ),
    ]
