# Generated by Django 3.1.3 on 2022-10-26 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0005_delete_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image6',
        ),
    ]
