# Generated by Django 4.0.2 on 2022-10-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0009_rename_creationdate_signup_regdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='regdate',
            new_name='creationdate',
        ),
    ]
