# Generated by Django 3.1.3 on 2022-10-29 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0010_rename_regdate_signup_creationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingnumber', models.CharField(blank=True, max_length=100, null=True)),
                ('bookingdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('productname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textapp.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='textapp.signup')),
            ],
        ),
    ]
