# Generated by Django 4.0.2 on 2022-10-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0012_booking_address_booking_fromdate_booking_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='totalprice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
