# Generated by Django 3.1.3 on 2022-11-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0017_booking_totalbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='monthyear',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='saleamount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
