# Generated by Django 5.1.6 on 2025-04-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0018_auto_20221108_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('UPI', 'UPI'), ('Credit/Debit Card', 'Credit/Debit Card'), ('Wallet', 'Wallet'), ('GPay', 'GPay'), ('PhonePe', 'PhonePe')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
