# Generated by Django 4.0.2 on 2022-10-11 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(blank=True, max_length=100, null=True)),
                ('brandlogo', models.FileField(blank=True, null=True, upload_to='')),
                ('creationdate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(blank=True, max_length=100, null=True)),
                ('productname', models.CharField(blank=True, max_length=100, null=True)),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('screen', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=100, null=True)),
                ('storage', models.CharField(blank=True, max_length=100, null=True)),
                ('charges', models.CharField(blank=True, max_length=100, null=True)),
                ('rentalprice', models.CharField(blank=True, max_length=100, null=True)),
                ('productmodel', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('creationdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('image1', models.FileField(blank=True, null=True, upload_to='')),
                ('image2', models.FileField(blank=True, null=True, upload_to='')),
                ('image3', models.FileField(blank=True, null=True, upload_to='')),
                ('image4', models.FileField(blank=True, null=True, upload_to='')),
                ('image5', models.FileField(blank=True, null=True, upload_to='')),
                ('image6', models.FileField(blank=True, null=True, upload_to='')),
                ('brandname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='textapp.brand')),
            ],
        ),
    ]
