# Generated by Django 4.0.2 on 2022-10-27 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('textapp', '0007_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='email',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='mobileno',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='pwd',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='secondname',
        ),
        migrations.AddField(
            model_name='signup',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
