# Generated by Django 4.0.2 on 2022-10-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0008_rename_email_signup_mobile_remove_signup_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='creationdate',
            new_name='regdate',
        ),
    ]
