# Generated by Django 3.1.3 on 2022-11-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0014_trackinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='totaldays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
