# Generated by Django 3.1.3 on 2022-11-05 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0015_booking_totaldays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackinghistory',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='trackinghistory',
            name='product',
        ),
    ]
