# Generated by Django 4.0.2 on 2022-11-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0016_auto_20221105_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='totalbooking',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
