from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('user_signup/', views.user_signup, name='user_signup'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('product_detail/<int:pid>/', views.product_detail, name='product_detail'),
    path('view_booking/<int:pid>/', views.view_booking, name='view_booking'),
    path('invoice/<int:pid>/', views.invoice, name='invoice'),
    path('book_laptop/<int:pid>/', views.book_laptop, name='book_laptop'),
    path('shop_page/', views.shop_page, name='shop_page'),
    path('laptop/', views.laptop, name='laptop'),
    path('desktop/', views.desktop, name='desktop'),
    path('edit_about/', views.edit_about, name='edit_about'),
    path('about/', views.about, name='about'),
    path('edit_contact/', views.edit_contact, name='edit_contact'),
    path('contact/', views.contact, name='contact'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login_admin/', views.login_admin, name='login_admin'),
    path('logout_admin/', views.logout_admin, name='logout_admin'),
    path('add_brand/', views.add_brand, name='add_brand'),
    path('view_brand/', views.brand, name='view_brand'),
    path('edit_brand/<int:pid>/', views.edit_brand, name='edit_brand'),
    path('delete_brand/<int:pid>/', views.delete_brand, name='delete_brand'),
    path('add_product/', views.add_product, name='add_product'),
    path('view_product/', views.product, name='view_product'),
    path('edit_product/<int:pid>/', views.edit_product, name='edit_product'),
    path('delete_product/<int:pid>/', views.delete_product, name='delete_product'),
    path('my_booking/', views.my_booking, name='my_booking'),
    path('new_booking/', views.new_booking, name='new_booking'),
    path('delete_booking/<int:pid>/', views.delete_booking, name='delete_booking'),
    path('booking/', views.booking, name='booking'),
    path('change_password/', views.change_password, name='change_password'),
    path('user_change_password/', views.user_change_password, name='user_change_password'),
    path('booking_detail/<int:pid>/', views.booking_detail, name='booking_detail'),
    path('change_status/<int:bid>/', views.change_status, name='change_status'),
    path('admin_report/', views.admin_report, name='admin_report'),
    path('count_report/', views.count_report, name='count_report'),
    path('reg_user/', views.reg_user, name='reg_user'),
    path('delete_user/<int:pid>/', views.delete_user, name='delete_user'),
    path('search_booking/', views.search_booking, name='search_booking'),
    path('report/', views.report, name='report'),
]
